### PR TITLE
Update to Lock 10.4 and extended possibility of modifying login / signin and logout components

### PR DESCRIPTION
**Pull request by CapChrisCap**
Your project is very nice but for me the support for Lock 10.4 was missing as well as the customization of the components. Now, the Login and Logout components are able to have a custom href and title. Furthermore, I added a possibility to add options to the LoginSignup component. Last but not least, I added the compiled lib and es folder to the project because otherwise it could be difficult to integrate those modules in tests. 

I would be glad if you would merge my version. If there are any questions or lacks of clarity, please feel free to ask.

### CODE REVIEW

**Comment by jadehopepunk** [comment]
I've tried out the version from @CapChrisCap . Overall it's great and I'd love to see it merged in. Using Auth0 Lock 10.x gives a nicer experience, and some of the other changes are great too.

I have only two minor gripes with the pull request.

## 1
The <LoginSignup> component has internal helper components for LoginButton and SignUpButton. That's fine, but they both have a propType specifying that their children should be of PropTypes.element. That means that if their child is just a simple string, React raises a warning. Since they use a string by default, this means the warning is thrown by default. To use the component and avoid the error, I had to wrap children in an unecessary span, eg: ```<LoginSignup login><span>Sign in</span></LoginSignup>```

I'd recommend just removing this propType for children completely.

## 2
The dependencies in package.json look a bit dodgy.

```  "dependencies": {
    "auth0-lock": "^9.0.6",
    "cacheable": "^0.2.9",
    "html-webpack-plugin": "^2.16.0",
    "namespaced-constants": "0.0.1",
    "redux-modifiers": "0.0.5",
    "webpack-hot-middleware": "^2.10.0"
  },
```
In particular this package requires in auth0-lock version 9.0.6, although this isn't actually used. The package continues @calvinfroedge 's assumption that you'll require auth0-lock from CDN. I'm doing that with version 10, and it all works expected, so it's silly that it has a dependency on auth0-lock at all.  Also some of those other dependencies look like they might be dev dependencies only. html-webpack-plugin and webpack-hot-middleware for example. 

---

Overall, this is a great package. It's a way better way of interacting with Auth0 for those of us using Redux, and it'd be great to see it get more love. If we can bring it up to date with this pull request, then I'd be happy to submit some changes too, such as better documentation.

**Comment by calvinfroedge** [comment]
Thanks for comments @craigambrose 

I agree with both of the points you brought up. I was apprehensive about @CapChrisCap having lib / es folders in project.

**Comment by CapChrisCap** [comment]
Yes, I added them because otherwise I use this module actively in a project and the tests for this project fails without using a builded version. Of course, I know that you build the code before you publish it, but in that time I forked this project, I was under time pressure and therefore I had no time to wait for the next release of your code. So I decided to just publish the builded code to run my tests. If you want, I can remove these folders again and update my pull request.

**Comment by calvinfroedge** [comment]
@CapChrisCap If you remove the compiled files from the PR I will accept it.

**Comment by calvinfroedge** [comment]
I implemented the new version of Auth0, so I'm going to close this PR. I did actually refer to it though when updating the code, there was just too much non-relevant stuff (i.e. the lib / es folders) for me to merge as is. Thanks for the PR regardless @CapChrisCap

**Pull request closed without merging**
